/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addAccountNode(name: string, configDir?: string | undefined | null): string

export declare function cycleDisableNode(configDir?: string | undefined | null): string

export declare function cycleEnableNode(configDir?: string | undefined | null): string

export declare function cycleNowNode(force?: boolean | undefined | null, configDir?: string | undefined | null): string

export declare function getConfigDirNode(): string

export declare function getCycleConfigNode(configDir?: string | undefined | null): string

export declare function getCycleStatusNode(configDir?: string | undefined | null): string

export declare function getUsageNode(account?: string | undefined | null, configDir?: string | undefined | null, refresh?: boolean | undefined | null): string

export declare function listAccountsNode(configDir?: string | undefined | null): string

export declare function removeAccountNode(name: string, configDir?: string | undefined | null): string

export declare function runCliNode(args: Array<string>): string

export declare function setCycleConfigNode(configDir?: string | undefined | null, fiveHour?: number | undefined | null, weekly?: number | undefined | null, mode?: string | undefined | null): string

export declare function switchAccountNode(name: string, configDir?: string | undefined | null, force?: boolean | undefined | null): string
